### PR TITLE
Add polygon mesh support

### PR DESCRIPTION
**Pull request by rjoomen**

### CODE REVIEW

**Comment by Levi-Armstrong** [comment]
Why do you have to use PolygonMesh directly versus using Mesh or ConvexHull type?

**Comment by rjoomen** [comment]
I was experimenting with meshing of point clouds (using PCL) and noticed PolygonMesh support was incomplete in an unexpected way. I agree it's not the best format, and also it's not supported in the contact checkers, but at least this makes some of the support for it more complete.

**Comment by rjoomen** [comment]
Is this good to go?

**Comment by Levi-Armstrong** [comment]
I think it is fine that the message interface supports the Polygon Mesh, but it should be converted it to a Mesh which is internally supported. I have code somewhere which will do this.

**Comment by rjoomen** [comment]
Is automatic conversion necessary? This PR simply enables communication of polygon meshes, what the user does with the data is up to him (including conversion).
Adding conversion functions to tesseract in general is useful though, but that would be a separate PR.

**Comment by Levi-Armstrong** [comment]
I checked Bullet and FCL which will throw an exception if this geometry type is used, so I am okay with this change.

**Pull request merged**
