### PR TITLE
0.14 parity

### PR DESCRIPTION
**Pull request by marrts**
Updating to match with all Tesseract tags 0.14.0

### CODE REVIEW

**Comment by marrts** [comment]
@Levi-Armstrong I think this is failing CI primarily because of the docker setup. Any recommendation on how I should configure the CI .yml files? I think all the images used for the other Tesseract builds are using ROS and catkin, so I don't know that I could just use one of those.

**Comment by rjoomen** [comment]
Relates to #34.

**Comment by rjoomen** [comment]
I have done more work one this, see [this PR](https://github.com/marrts/tesseract_ros2/pull/4). This includes a working CI configuration for Ubuntu 22.04/ROS2 Humble.

Question: which Ubuntu and ROS2 versions should be supported?

**Comment by marrts** [comment]
Looking through your PR and hoping to test it out relatively soon, thanks! 

> Question: which Ubuntu and ROS2 versions should be supported?

I personally haven't done anything in Humble yet, that's why you won't see anything relating to it used at all in my PR, but I assume it would make the most sense to support Foxy and Humble for now.

**Comment by rjoomen** [comment]
Thanks! I'll do a Focal/Foxy install here and investigate the build problems.

**Comment by marrts** [comment]
If necessary we might need to do 2 separate branches. Have the main branch be built on top of Humble and then have a Foxy branch. I'm not sure of all the breaking changes between the two.

**Comment by rjoomen** [comment]
I fixed the build for Focal/Foxy, so I don't think 2 branches are necessary.

I had to remove `rclcpp::SubscriptionOptions` from `current_state_monitor.cpp` though, as that seems to be newer functionality, but I think we can do without.

**Comment by Levi-Armstrong** [comment]
@marrts It looks like @rjoomen created a PR agains your branch that resolved the remaining issues.

**Pull request merged**
