### PR TITLE
Fix clocks (wall/sim time) to match tesseract_ros

### PR DESCRIPTION
**Pull request by rjoomen**

### CODE REVIEW

**Comment by rjoomen** [comment]
@marrts could you review?

**Comment by rjoomen** [comment]
@marrts / @Levi-Armstrong, could you please review?

**Comment by Levi-Armstrong** [comment]
I see places where it used RCL_STEADY_TIME and others it does not. Is this intended?

**Comment by rjoomen** [comment]
It vaguely was, but I think I can better swap out the RCL_STEADY_TIME for RCL_SYSTEM_TIME for uniformity.  Oh, and the one in waitForCurrentState() is wrong I just noticed, that should be RCL_ROS_TIME, as it's compared with node->now(). I'll update the PR.

**Comment by rjoomen** [comment]
Forget my previous (deleted) comment, I was mistaken.

I intentionally use RCL_ROS_TIME for node time, which might be simulated. So rclcpp::Clock{ RCL_ROS_TIME }.now() should be equivalent to ros::Time::now(). I used RCL_STEADY_TIME for a wall clock timeout. So rclcpp::Clock{ RCL_STEADY_TIME }.now() should be equivalent to ros::WallTime::now(), when used for a timer (i.e. the time difference and not the actual time is of interest). I could also have used RCL_SYSTEM_TIME here, but a steady clock is specifically designed for timing cases.

**Comment by marrts** [comment]
Have all of the occurrences of these clocks been tested? I know in the past I've had issues trying to do a comparison between time values that have different clock types as sources.

**Comment by rjoomen** [comment]
I'm using it now and didn't have clock issues yet. The steady clocks are only used locally, all other clocks should be ROS clocks.

The only issue I had was with ROSEnvironmentMonitor, where the *_time_ members were not initialized yet, but the newEnvironmentStateCallback() was already called. This threw a clock comparison error, which I fixed by adding the time_ members to the initializer list. But this is not really a clock problem, but a initialization/concurrency problem, hence my plan to commit it in a separate update.

**Comment by marrts** [comment]
This is working for me as well.

**Pull request merged**
