### PR TITLE
Removed dependency on Qt ADS repo and Gazebo

### PR DESCRIPTION
**Pull request by marip8**
Changes per commit message

### CODE REVIEW

**Comment by Levi-Armstrong** [comment]
These are required to tesseract_qt_ros and should be maintained for the purpose of CI.

**Comment by marip8** [comment]
`tesseract_qt_ros` currently has a `COLCON_IGNORE`, so my impression was that it was dev feature that's not complete or supported.

**Comment by Levi-Armstrong** [comment]
Huh, from a ros perspective there is not much in here so it should not be hard to get it functioning.

**Comment by marip8** [comment]
Would there be any reason that package couldn't live as a subdirectory of `tesseract_qt` instead? I don't exactly know what it does but it seems like a plugin for the studio; it seems like it might be more related to the studio stuff than the ROS stuff in this repo. Seems like you could optionally build it and use CMake to find the necessary ROS components to build it

**Comment by Levi-Armstrong** [comment]
> Would there be any reason that package couldn't live as a subdirectory of tesseract_qt instead? I don't exactly know what it does but it seems like a plugin for the studio; it seems like it might be more related to the studio stuff than the ROS stuff in this repo. Seems like you could optionally build it and use CMake to find the necessary ROS components to build it

It has ros plugin along with a studio node which is ros compatible. I do not want any of the tesseract ros agnostic repositories to have connection to ros components even if they are optional. This is in its own package so if you do not want the dependencies it can be ignored.

**Comment by marip8** [comment]
That's fine. I think let's ignore it for now until we have time to make sure its fully supported. I would like to get Docker images generated for downstream projects for 0.18 and 0.19

**Review by Levi-Armstrong — APPROVED** [review]

**Pull request merged**
